"""3D / Cl(3,1) Minkowski representation of Descartes quadruples.

A Descartes quadruple of curvatures b = (b_0, b_1, b_2, b_3) satisfies
the Descartes form

    F(b) = 2 (b_0^2 + b_1^2 + b_2^2 + b_3^2) - (b_0 + b_1 + b_2 + b_3)^2 = 0.

F is a quadratic form of Minkowski signature (1, 3). The polarised form is

    <a, b>_M = (sum a_i) (sum b_i) - 2 sum a_i b_i

so that F(b) = <b, b>_M. The Apollonian group is the integer subgroup of
the indefinite orthogonal group O(F) ~= O(1, 3) that preserves F; it is
generated by four involutions

    S_i: b_i -> 2 (sum_{j != i} b_j) - b_i,   b_j -> b_j  for j != i

which swap each curvature with its Apollonian partner.

For embedding purposes we work on the unit hyperboloid

    H = { b in R^4 :  <b, b>_M = c,   sum b_i > 0 },

where c > 0 is a fixed positive constant. Geodesics on H are intersections
with 2-planes through the origin, so the geodesic distance and log map have
closed forms in terms of acosh and a tangent projection -- exactly the
machinery needed for a "cone on the hyperboloid" attention layer.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np


# ---------------------------------------------------------------------------
# Minkowski quadratic + bilinear forms
# ---------------------------------------------------------------------------

def descartes_form(b: np.ndarray) -> float | np.ndarray:
    """F(b) = 2*sum(b_i^2) - (sum b_i)^2. Zero on Descartes quadruples."""
    b = np.asarray(b)
    return 2.0 * (b ** 2).sum(axis=-1) - b.sum(axis=-1) ** 2


def minkowski_inner(a: np.ndarray, b: np.ndarray) -> float | np.ndarray:
    """Polarised Descartes form: <a, b>_M = (sum a)(sum b) - 2 sum(a*b).

    Beware the sign: with this convention F(b) = -<b, b>_M (off by an overall
    minus, since F(b) = 2 sum b^2 - (sum b)^2 = -[(sum b)^2 - 2 sum b^2]).
    We use the convention where Descartes quadruples are LIGHTLIKE
    (<b, b>_M = 0). Timelike vectors (<b,b>_M > 0) are off-shell, useful as
    embeddings of "concept regions".
    """
    a = np.asarray(a); b = np.asarray(b)
    return a.sum(axis=-1) * b.sum(axis=-1) - 2.0 * (a * b).sum(axis=-1)


def minkowski_norm_sq(b: np.ndarray) -> float | np.ndarray:
    """<b, b>_M. Note: this equals -F(b)."""
    return minkowski_inner(b, b)


# ---------------------------------------------------------------------------
# Apollonian group: the four coordinate reflections
# ---------------------------------------------------------------------------

def apollonian_reflection(b: np.ndarray, i: int) -> np.ndarray:
    """S_i: replace b_i with 2*(sum of others) - b_i."""
    b = np.asarray(b, dtype=float).copy()
    others_sum = b.sum(axis=-1) - b[..., i]
    b[..., i] = 2.0 * others_sum - b[..., i]
    return b


REFLECTION_MATRICES: list[np.ndarray] = []
for _i in range(4):
    M = np.eye(4)
    M[_i, _i] = -1.0
    for _j in range(4):
        if _j != _i:
            M[_i, _j] = 2.0
    REFLECTION_MATRICES.append(M)
del _i, _j, M


def is_descartes(b: np.ndarray, tol: float = 1e-6) -> bool:
    return bool(abs(descartes_form(b)) < tol)


# ---------------------------------------------------------------------------
# Lifting a circle's neighbourhood into a 4-vector embedding
# ---------------------------------------------------------------------------

def quadruple_4vector(curvatures: tuple[float, float, float, float]) -> np.ndarray:
    """Wrap a Descartes 4-tuple as a numpy 4-vector (no checks)."""
    return np.asarray(curvatures, dtype=float)


def lift_circle(b_self: float, b_neighbors: tuple[float, float, float]) -> np.ndarray:
    """The natural 4-vector for a circle in the gasket is the Descartes tuple
    (b_self, b_n1, b_n2, b_n3) of itself + its three Apollonian neighbours --
    this *is* a Descartes quadruple by construction.
    """
    return np.array([b_self, *b_neighbors], dtype=float)


# ---------------------------------------------------------------------------
# Hyperboloid model: timelike normalisation + geodesics
# ---------------------------------------------------------------------------

@dataclass
class HyperboloidPoint:
    """A timelike unit vector: <u, u>_M = +1, sum u_i > 0."""

    u: np.ndarray  # shape (4,)

    def __post_init__(self) -> None:
        self.u = np.asarray(self.u, dtype=float)


def to_hyperboloid(b: np.ndarray, eps: float = 1e-9) -> HyperboloidPoint:
    """Rescale a timelike 4-vector so <u, u>_M = +1 (project onto H^3).

    WARNING — NOT the right model for gasket embedding. A Descartes quadruple
    is LIGHTLIKE (<b, b>_M = -F(b) = 0), so it does not lie on the timelike
    hyperboloid. The eps-nudge below forces it on by inflating the (1,1,1,1)
    component, which collapses every gasket circle toward the same apex — this
    is exactly why the Phase-A hyperboloid embedding failed in experiment 06.
    For embedding gasket circles use the upper-half-space model in `ael.uhs`
    (which gave the working Phase-A results in experiment 07). This function is
    kept only for genuinely timelike (off-shell) inputs and that comparison.
    """
    b = np.asarray(b, dtype=float)
    if b.sum() <= 0:
        b = -b  # pick the upper sheet
    n2 = minkowski_norm_sq(b)
    # A spacelike or lightlike input (n2 <= 0) has no place on the timelike
    # hyperboloid. Nudge toward the timelike apex (1,1,1,1) until strictly
    # timelike -- Q(b + t*ones) -> +inf as t grows, so this always terminates.
    # (Adding a single fixed eps did NOT guarantee timelike and could leave
    # n2 < 0, crashing math.sqrt.)
    t = max(eps, 1e-9)
    while n2 <= eps:
        b = b + t * np.ones(4)
        n2 = minkowski_norm_sq(b)
        t *= 10.0
    return HyperboloidPoint(u=b / math.sqrt(float(n2)))


def hyper_dist(u: HyperboloidPoint, v: HyperboloidPoint) -> float:
    """Geodesic distance on H^3: d(u, v) = acosh(<u, v>_M)."""
    ip = float(minkowski_inner(u.u, v.u))
    # Numerical clamp.
    if ip < 1.0:
        ip = 1.0
    return math.acosh(ip)


def hyper_log(u: HyperboloidPoint, v: HyperboloidPoint) -> np.ndarray:
    """Logarithm map at u: returns a tangent vector at u pointing toward v.

    log_u(v) = (theta / sinh(theta)) * (v - cosh(theta) * u),
    where theta = d(u, v).

    The returned vector is in the tangent space T_u H, i.e. orthogonal to u
    in the Minkowski metric: <log_u(v), u>_M = 0.
    """
    ip = float(minkowski_inner(u.u, v.u))
    if ip <= 1.0:
        return np.zeros_like(u.u)
    theta = math.acosh(ip)
    sh = math.sinh(theta)
    if sh < 1e-12:
        return np.zeros_like(u.u)
    return (theta / sh) * (v.u - ip * u.u)


def tangent_unit_axis(u: HyperboloidPoint, axis_unnormalised: np.ndarray) -> np.ndarray:
    """Project an ambient 4-vector to the tangent space at u and normalise.

    Tangent space at u: { w in R^4 : <w, u>_M = 0 }.

    The Minkowski form is signature (1, 3) with the single positive
    eigendirection along (1,1,1,1). At a timelike unit vector u that positive
    direction is spanned by u itself, so on the orthogonal complement T_u the
    form is NEGATIVE-definite. The induced Riemannian metric on the hyperboloid
    is therefore g(w, w) = -<w, w>_M >= 0, and we normalise in g (verified
    empirically: 980/1000 random tangent vectors have <w,w>_M < 0, none > 0).
    """
    w = np.asarray(axis_unnormalised, dtype=float)
    # Remove the u-component (in the Minkowski metric) so <w, u>_M = 0.
    w = w - minkowski_inner(w, u.u) * u.u
    # Induced metric g(w, w) = -<w, w>_M. Clamp at 0 rather than abs() so a
    # genuinely spacelike (positive <w,w>_M) input surfaces as ~0 instead of
    # being silently accepted.
    g = -float(minkowski_inner(w, w))
    n = math.sqrt(max(g, 0.0))
    if n < 1e-12:
        return w
    return w / n
